services:
  convert:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/preprocessing/convert_tif_to_png.py
    volumes:
      - ./src:/app/src
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

  split:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/preprocessing/split_images.py
    volumes:
      - ./src:/app/src
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

  inference:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/inference/run_model.py
    volumes:
      - ./src:/app/src
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}