FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy model code and utils
COPY src/inference/ ./inference/
COPY src/model/ ./model/
COPY src/utils/ ./utils/

CMD ["python", "-m", "inference.run_model"]